# Generated by Django 4.2.1 on 2023-06-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster_app', '0004_monster_ip_list'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnregisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='', max_length=200)),
                ('monsters', models.ManyToManyField(to='monster_app.monster')),
            ],
        ),
    ]
