version: '3'

services:
  frontend:
    build: ./frontend/monster_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm start

  backend:
    build: ./monster_project
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:  
      DB_PASSWORD: mysecretpassword #TODO add to env file

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword #TODO add to env file
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
