# Generated by Django 4.2.1 on 2023-05-25 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monster_app', '0001_initial'),
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loser_monsters', to='monster_app.monster'),
        ),
        migrations.AddField(
            model_name='battle',
            name='loser_xp_gain',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='winner_xp_gain',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
