# Generated by Django 4.2.1 on 2023-05-29 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monster_app', '0001_initial'),
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='conflict_creature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conflict_monster', to='monster_app.monster'),
        ),
        migrations.AlterField(
            model_name='story',
            name='monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_monster', to='monster_app.monster'),
        ),
    ]
