# Generated by Django 4.2.1 on 2023-05-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_story_conflict_creature_alter_story_monster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
