# Generated by Django 4.2.1 on 2023-05-24 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attack', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('max_health', models.IntegerField(default=0)),
                ('max_attack', models.IntegerField(default=0)),
                ('max_xp', models.IntegerField(default=0)),
                ('conscious', models.BooleanField(default=True)),
                ('last_battle', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('gameentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monster_app.gameentity')),
                ('element_type', models.CharField(default='', max_length=200)),
                ('creature', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('monster_app.gameentity',),
        ),
    ]
