# Generated by Django 4.2.1 on 2023-05-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
