# Generated by Django 4.2.1 on 2023-06-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster_app', '0002_monster_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameentity',
            name='location_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameentity',
            name='location_y',
            field=models.IntegerField(default=0),
        ),
    ]
