# Generated by Django 4.2.1 on 2023-06-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landscape',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
