# Generated by Django 4.2.1 on 2023-06-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_landscape_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='landscape',
            name='feature',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='landscape',
            name='landscape_type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
