# Generated by Django 4.2.1 on 2023-06-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_landscape_feature_landscape_landscape_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='landscape',
            name='ip_list',
            field=models.TextField(default='[]'),
        ),
    ]
