# Generated by Django 4.2.1 on 2023-06-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_landscape_ip_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landscape',
            old_name='ip_list',
            new_name='user_ip_list',
        ),
        migrations.AddField(
            model_name='landscape',
            name='monster_ip_list',
            field=models.TextField(default='[]'),
        ),
    ]
